version: '3.9'

services:
  activemq-artemis:
    image: vromero/activemq-artemis:latest
    restart: always
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - 61616:61616
      - 8161:8161
    expose:
      - 61616
      - 8161

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: orders
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306

  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017