eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: true
