spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}
      authentication-database: ${MONGO_AUTHENTICATION_DATABASE:admin}
      port: ${MONGO_PORT:27017}
      database: email_order
  artemis:
    mode: native
    broker-url: tcp://${ARTEMIS_HOST:localhost}:${ARTEMIS_PORT:61616}
    user: ${ARTEMIS_USER:admin}
    password: ${ARTEMIS_PASSWORD:admin}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    # username: ${MAIL_USERNAME:your_email@your_domain.com}
    # password: ${MAIL_PASSWORD:your_password}
    properties:
      mail:
        smtp:
          auth: ${MAIL_PROPERTIES_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_PROPERTIES_SMTP_AUTH_STARTTLS:true}
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftlh
    expose-spring-macro-helpers: true

# email:
#   from: ${EMAIL_FROM:your_email@your_domain.com}

server:
  port: 8200