spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:orders}
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: liquibase/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9999}/realms/${KEYCLOAK_REALM:pd-commerce}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    queue: ${RABBITMQ_QUEUE:order.email.queue}

springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /documentation

server:
  port: 8100