spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/products
    driver-class-name: org.h2.Driver
    username: pdProducts
    password: master
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  artemis:
    mode: native
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
    user: ${ARTEMIS_USER:felipemaxplay}
    password: ${ARTEMIS_PASSWORD:adminpwd}

server:
  port: 8000