spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:products}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  artemis:
    mode: native
    broker-url: tcp://${ARTEMIS_HOST:localhost}:${ARTEMIS_PORT:61616}
    user: ${ARTEMIS_USER:admin}
    password: ${ARTEMIS_PASSWORD:admin}
  liquibase:
    change-log: liquibase/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:9999}/realms/${KEYCLOAK_REALM:pd-commerce}

springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /documentation

server:
  port: 8000